
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 28 20:20:17 CEST 2014
//----------------------------------------------------

package compiler.synanal;

/** CUP generated class containing symbol constants. */
public class PascalTok {
  /* terminals */
  public static final int CHAR_CONST = 3;
  public static final int VAL = 38;
  public static final int LTH = 28;
  public static final int FUNCTION = 47;
  public static final int LBRACKET = 14;
  public static final int CONST = 42;
  public static final int CHAR = 8;
  public static final int SEMIC = 18;
  public static final int INT = 9;
  public static final int ARRAY = 39;
  public static final int FOR = 46;
  public static final int NOT = 32;
  public static final int AND = 22;
  public static final int RECORD = 52;
  public static final int TYPE = 55;
  public static final int NIL = 5;
  public static final int OR = 33;
  public static final int BOOL = 7;
  public static final int COMMA = 11;
  public static final int BEGIN = 41;
  public static final int DIV = 23;
  public static final int GEQ = 25;
  public static final int IF = 48;
  public static final int ASSIGN = 40;
  public static final int UADD = 36;
  public static final int DOT = 12;
  public static final int PTR = 34;
  public static final int OF = 49;
  public static final int DOTS = 13;
  public static final int EOF = 0;
  public static final int RBRACKET = 16;
  public static final int INT_CONST = 4;
  public static final int PROGRAM = 51;
  public static final int error = 1;
  public static final int MUL = 30;
  public static final int ADD = 21;
  public static final int LPARENTHESIS = 15;
  public static final int NEQ = 31;
  public static final int AUTO = 19;
  public static final int GTH = 26;
  public static final int EQU = 24;
  public static final int COLON = 10;
  public static final int ELSE = 44;
  public static final int TO = 54;
  public static final int MEM = 29;
  public static final int WHILE = 57;
  public static final int QUEST = 20;
  public static final int THEN = 53;
  public static final int RPARENTHESIS = 17;
  public static final int LEQ = 27;
  public static final int END = 45;
  public static final int USUB = 37;
  public static final int BOOL_CONST = 2;
  public static final int SUB = 35;
  public static final int VAR = 56;
  public static final int PROCEDURE = 50;
  public static final int DO = 43;
  public static final int IDENTIFIER = 6;

  /* non terminals */
  static final int subprograms = 7;
  static final int statement = 28;
  static final int constant = 12;
  static final int types_list = 9;
  static final int type = 13;
  static final int parameter = 20;
  static final int function = 17;
  static final int parameters = 18;
  static final int procedure = 16;
  static final int block = 30;
  static final int program = 2;
  static final int vars_list = 10;
  static final int components_list = 22;
  static final int empty = 0;
  static final int argument = 27;
  static final int component = 23;
  static final int types = 5;
  static final int value_expression = 24;
  static final int vars = 6;
  static final int subprogram = 15;
  static final int const_list = 8;
  static final int declarations = 3;
  static final int source = 1;
  static final int type_expression = 21;
  static final int arguments_list = 26;
  static final int statements = 29;
  static final int parameters_list = 19;
  static final int var = 14;
  static final int subprograms_list = 11;
  static final int arguments = 25;
  static final int constants = 4;
}

